"""
Pydantic Schemas for the SatQuery AI Central Orchestration Layer.

Defines standardized data models for:
- User queries & multi-modal inputs
- Agent registry metadata
- Standardized agent execution outputs
- Execution trace tracking & stages
- Result aggregation & final responses
"""

from enum import Enum
from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field


class AgentType(str, Enum):
    """Supported agent types in the SatQuery AI ecosystem."""
    VQA = "vqa"
    GROUNDING = "grounding"
    CHANGE_DETECTION = "change_detection"
    OPTICAL_SAR = "optical_sar"
    AREA_MANAGEMENT = "area_management"
    RAG = "rag"


class AgentStatus(str, Enum):
    """Execution status for an individual agent."""
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"


class AgentMetadata(BaseModel):
    """Metadata describing a registered agent."""
    id: AgentType
    name: str
    description: str
    supported_tasks: List[str]
    required_inputs: List[str]
    optional_inputs: List[str] = Field(default_factory=list)
    output_types: List[str]


class ImageEvidence(BaseModel):
    """Visual evidence produced from satellite imagery analysis."""
    type: str = Field(..., description="Type of visual evidence (bounding_boxes, change_mask, annotated_image, etc.)")
    title: str = Field(..., description="Human-readable title")
    url_or_b64: Optional[str] = Field(default=None, description="Image URL or base64 string")
    file_path: Optional[str] = Field(default=None, description="Path on disk if available")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional properties (coordinates, metrics, etc.)")


class KnowledgeEvidence(BaseModel):
    """Domain knowledge evidence produced from the project's knowledge base."""
    text: str = Field(..., description="Retrieved snippet of domain knowledge")
    source: str = Field(..., description="Document source filename")
    section: Optional[str] = Field(default=None, description="Document section or header")
    category: Optional[str] = Field(default="remote_sensing", description="Knowledge category")
    score: Optional[float] = Field(default=None, description="Retrieval similarity score")


class StandardizedAgentOutput(BaseModel):
    """
    Standardized internal result produced by any agent adapter.
    Normalizes outputs from all 6 specialized agents.
    """
    agent: AgentType
    agent_name: str
    status: AgentStatus = AgentStatus.SUCCESS
    answer: str = Field(default="", description="Textual finding or answer from this agent")
    confidence: Optional[float] = Field(default=None, description="Agent confidence score (0.0 to 1.0)")
    bounding_boxes: List[Dict[str, Any]] = Field(default_factory=list, description="Detected object boxes if any")
    masks: List[Dict[str, Any]] = Field(default_factory=list, description="Segmentation or change masks if any")
    change_regions: List[Dict[str, Any]] = Field(default_factory=list, description="Detected change regions if any")
    measurements: Dict[str, Any] = Field(default_factory=dict, description="Area, count, or pixel measurements")
    image_evidence: List[ImageEvidence] = Field(default_factory=list, description="Visual evidence items")
    knowledge_evidence: List[KnowledgeEvidence] = Field(default_factory=list, description="RAG domain knowledge items")
    execution_time_seconds: float = Field(default=0.0)
    raw_output: Optional[Dict[str, Any]] = Field(default=None, description="Underlying raw output if needed")
    error: Optional[str] = Field(default=None, description="Error message if execution failed")


class ExecutionStepTrace(BaseModel):
    """Trace entry for a single stage in the orchestration process."""
    step: int
    name: str
    description: str
    status: str = "completed"  # pending, running, completed, warning, failed
    duration_seconds: float = 0.0
    details: Optional[Dict[str, Any]] = None


class ExecutionTrace(BaseModel):
    """Comprehensive execution trace for auditability and transparency."""
    request_id: str
    timestamp: str
    user_query: str
    detected_intent: str
    selected_agents: List[AgentType]
    selection_reasoning: str
    execution_order: List[List[AgentType]] = Field(default_factory=list, description="Batches of agents executed")
    steps: List[ExecutionStepTrace] = Field(default_factory=list)
    total_duration_seconds: float = 0.0
    errors: List[str] = Field(default_factory=list)


class OrchestrationPlan(BaseModel):
    """The plan generated by Query Understanding before execution."""
    intent: str
    primary_goal: str
    requires_temporal: bool = False
    requires_grounding: bool = False
    requires_change: bool = False
    requires_sar: bool = False
    requires_area: bool = False
    requires_rag: bool = False
    is_ambiguous: bool = False
    clarification_message: Optional[str] = None
    selected_agents: List[AgentType]
    execution_order: List[List[AgentType]]
    selection_reasoning: str
    missing_inputs: List[str] = Field(default_factory=list)


class OrchestratorQueryRequest(BaseModel):
    """Incoming request to the central orchestrator."""
    query: str = Field(..., min_length=1, description="Natural language question or command")
    image_ids: Optional[List[str]] = Field(default=None, description="List of preset or uploaded image IDs")
    image_b64s: Optional[List[str]] = Field(default=None, description="List of Base64-encoded images")
    timestamps: Optional[List[str]] = Field(default=None, description="Optional temporal dates/timestamps (e.g. ['2022', '2026'])")
    modality: Optional[str] = Field(default=None, description="Optional sensor modality hint (Optical, SAR, etc.)")
    box_threshold: Optional[float] = Field(default=0.20, description="Confidence threshold for grounding")
    force_satellite_mode: Optional[bool] = Field(default=True, description="Satellite color-space optimization for area")


class OrchestratorQueryResponse(BaseModel):
    """Unified response returned to the user and frontend."""
    success: bool = True
    query: str
    intent: str
    agents_used: List[str]
    answer: str
    confidence: Optional[float] = None
    confidence_display: str = "N/A"
    image_evidence: List[ImageEvidence] = Field(default_factory=list)
    knowledge_evidence: List[KnowledgeEvidence] = Field(default_factory=list)
    measurements: Dict[str, Any] = Field(default_factory=dict)
    bounding_boxes: List[Dict[str, Any]] = Field(default_factory=list)
    trace: ExecutionTrace
    requires_clarification: bool = False
    clarification_options: Optional[List[str]] = None
    structured_for_ui: Optional[Dict[str, Any]] = Field(default=None, description="Pre-formatted object for AnalysisResults.jsx")
